# Site settings
title: No Bulbs
email: leon.paternoster@zoho.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal, nonwork blog from Leon Paternoster.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nobulbs.com" # the base hostname & protocol for your site
twitter_username: leonpaternoster
github_username:  leonp

# Build settings
markdown: kramdown
permalink: /:title/
